theme: jekyll-theme-hacker
title: 🛡️ VEN Alliance Hub
description: "Train • Rally • Conquer • Grow Together ⚔️ <br> Everything you need to master Kingshot—Bear Trap, Events, Hero Builds, Battle Guides, Alliance Tips, and much more. Built by VEN, for VEN. 💙 <br><br> 🚧 Work in Progress: New guides, strategies, and updates will be added regularly."
