theme: jekyll-theme-hacker
title: 🛡️ VEN Alliance Hub
description: Train • Rally • Conquer • Grow Together ⚔️
Everything you need to master Kingshot—Bear Trap, Events, Hero Builds, Battle Guides, Alliance Tips, and much more. Built by VEN,for VEN. 💙
